addons:
  mariadb: '10.3'

language: perl
matrix:
  include:
  - perl: "5.30"
  - perl: "5.28"
  - perl: "5.26"
  - perl: "5.24"
  - perl: "5.22"
  - perl: "5.20"
    dist: trusty
  - perl: "5.18"
    dist: trusty
  - perl: "5.16"
    dist: trusty
  - perl: "5.14"
    dist: trusty
  - perl: "5.12"
    dist: trusty
  - perl: "5.10"
    dist: trusty

env: SUCC_DB_HOST=127.0.0.1 SUCC_DB_NAME=succession SUCC_DB_USER=test_user LYSTYNG_DB_PASS=a_sekrit

before_script:
  - mysql -e "create database $SUCC_DB_NAME;"
  - mysql -e "drop user if exists '$SUCC_DB_USER'@'$SUCC_DB_HOST';"
  - mysql -e 'flush privileges;'
  - mysql -e "create user '$SUCC_DB_USER'@'$SUCC_DB_HOST' identified by '$SUCC_DB_PASS';"
  - mysql -e "grant all on $SUCC_DB_NAME.* to '$SUCC_DB_USER'@'$SUCC_DB_HOST';"
  - mysql -D $SUCC_DB_NAME < data/succession_dump.sql

before_install:
  cpanm -n Devel::Cover::Report::Coveralls
script:
  cd Succession && perl Makefile.PL && make && cover -test -report coveralls
